# Generated by Django 4.1 on 2022-08-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=50, verbose_name='Name')),
                ('clientAge', models.IntegerField(verbose_name='Age')),
                ('clientWeight', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Weight')),
                ('clientHeight', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Weight')),
                ('clientAddress', models.TextField(verbose_name='Address')),
                ('clientJoinDate', models.DateField(verbose_name='Join Date')),
                ('clientPlan', models.CharField(max_length=50, verbose_name='Plan')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='empAddress',
            field=models.TextField(verbose_name='Address '),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empAge',
            field=models.IntegerField(verbose_name='Age '),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empName',
            field=models.CharField(max_length=50, verbose_name='Name '),
        ),
    ]
